# NumPy Retail Analytics Assignment

## Business Scenario

You are working as a Data Analyst for **SmartMart Retail Stores**. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

1. `sales_data` — monthly sales revenue generated by each store for different product categories.
2. `cost_data` — total cost incurred by each store for the same product categories.

# Part 1: Dataset Creation

In [1]:
import numpy as np
import pandas as pd

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

df_sales=pd.DataFrame(sales_data,index=stores,columns=categories)
print("\n",df_sales)

df_cost=pd.DataFrame(cost_data,index=stores,columns=categories)
print("\n",df_cost)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]

            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       850000     420000    310000     275000  190000  225000
Hyderabad       780000     460000    295000     310000  210000  240000
Chennai         920000     390000    340000     260000  185000  215000
Mumbai         1050000     510000    375000     345000  250000  290000
Pune            690000     405000    280000     225000  175000  205000

            Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       640000     315000    220000     205000  125000  160000
Hyderabad       590000     350000    210000     225000  140000  170000
Chennai         700000     295000    245000     195000  120000  155000
Mumbai          790000     390000    265000     250000  165000  205000
Pune            530000     310000    205000     170000  115000  145000

# Part 2: Basic Array Understanding

## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

In [46]:
print(f"dimensions of sales_data: {sales_data.ndim}\nshape of sales_data: {sales_data.shape}\ntotal no.of sales_data values: {sales_data.size}\ndata type of sales_data: {type(sales_data)}\nmemory occupied of sales_data: {sales_data.nbytes}")

dimensions of sales_data: 2
shape of sales_data: (5, 6)
total no.of sales_data values: 30
data type of sales_data: <class 'numpy.ndarray'>
memory occupied of sales_data: 240

## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

In [47]:
print(len(stores))
print(len(categories))
print(df_sales.size)

5
6
30

## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

In [48]:
folat32=sales_data.astype(np.float32)
folat64=sales_data.astype(np.float64)

print(f"float32: {folat32.nbytes} ,folat64: {folat64.nbytes}")

print(f"Memory saved: {folat64.nbytes - folat32.nbytes} bytes ({((folat64.nbytes - folat32.nbytes) / folat64.nbytes * 100):.1f}% reduction)")

float32: 120 ,folat64: 240
Memory saved: 120 bytes (50.0% reduction)

# Part 3: Indexing and Data Extraction

## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [49]:
print(df_sales.loc["Bengaluru"])

Electronics    850000
Groceries      420000
Clothing       310000
Furniture      275000
Beauty         190000
Sports         225000
Name: Bengaluru, dtype: int64

## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [50]:
print(sum(df_cost.loc["Mumbai"]))

2065000

## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.

In [62]:
print(df_sales.loc[:,df_sales.columns == "Electronics"])

           Electronics
Bengaluru       850000
Hyderabad       780000
Chennai         920000
Mumbai         1050000
Pune            690000

## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

In [63]:
print(df_cost.loc[:,df_cost.columns=="Clothing"])

           Clothing
Bengaluru    220000
Hyderabad    210000
Chennai      245000
Mumbai       265000
Pune         205000

## Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

In [67]:
furniture_sales=df_sales.loc["Hyderabad",df_sales.columns=="Furniture"].item()
furniture_cost=df_cost.loc["Hyderabad",df_cost.columns=="Furniture"].item()
furniture_profit=furniture_sales-furniture_cost
print(f"furniture_sales:{furniture_sales}\nfurniture_cost:{furniture_cost}\nfurniture_profit:{furniture_profit}")

furniture_sales:310000
furniture_cost:225000
furniture_profit:85000

## Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

In [79]:
chennai=df_sales.iloc[2,1:4]
print(chennai)

Groceries    390000
Clothing     340000
Furniture    260000
Name: Chennai, dtype: int64

## Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

In [ ]:
da = df_sales.loc[["Bengaluru", "Chennai", "Pune"],["Electronics", "Clothing", "Beauty"]]  
print(da)

           Electronics  Clothing  Beauty
Bengaluru       850000    310000  190000
Chennai         920000    340000  185000
Pune            690000    280000  175000

# Part 4: Sales Aggregation

## Question 11: Company-Wide Sales

Calculate the total sales revenue generated by all stores and all categories.

In [119]:
revenue_by_stores=df_sales.sum(axis=1)
print(f"total sales revenue generated by all stores: {sum(revenue_by_stores)}")
revenue_by_categories=df_sales.sum(axis=0)
print(f"total sales revenue generated by all categories :{sum(revenue_by_categories)}")

total sales revenue generated by all stores: 11675000
total sales revenue generated by all categories :11675000

## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format:

```text
Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [164]:
for i in df_sales.index:
    print(f"{i}: {sum(df_sales.loc[i])}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000

## Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [165]:
print(df_sales.sum(axis=0))

Electronics    4290000
Groceries      2185000
Clothing       1600000
Furniture      1415000
Beauty         1010000
Sports         1175000
dtype: int64

## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
print(df_sales.mean(axis=1))

Bengaluru    378333.333333
Hyderabad    382500.000000
Chennai      385000.000000
Mumbai       470000.000000
Pune         330000.000000
dtype: float64

## Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [176]:
print(df_sales.mean(axis=0))

Electronics    858000.0
Groceries      437000.0
Clothing       320000.0
Furniture      283000.0
Beauty         202000.0
Sports         235000.0
dtype: float64

## Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

Use `np.argmax()`.

In [186]:
print(np.argmax(df_sales.index))
print(np.max(df_sales.index))
print(np.max(df_sales.sum(axis=1)))

4
Pune
2820000

## Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use `np.argmin()`.

In [202]:
lowest_sale=np.argmin(df_sales.sum(axis=1).values)
print(df_sales.index[lowest_sale])

Pune

## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [233]:
high_sale=np.argmax(df_sales.sum(axis=0).values)
print(df_sales[categories[high_sale]])

Bengaluru     850000
Hyderabad     780000
Chennai       920000
Mumbai       1050000
Pune          690000
Name: Electronics, dtype: int64

## Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [234]:
high_sale=np.argmin(df_sales.sum(axis=0).values)
print(df_sales[categories[high_sale]])

Bengaluru    190000
Hyderabad    210000
Chennai      185000
Mumbai       250000
Pune         175000
Name: Beauty, dtype: int64

# Part 5: Cost Analysis

## Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [236]:
print(np.sum(cost_data))

8600000

## Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [5]:
print(df_cost.sum(axis=1))

Bengaluru    1665000
Hyderabad    1685000
Chennai      1710000
Mumbai       2065000
Pune         1475000
dtype: int64

## Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [6]:
print(df_cost.sum(axis=0))

Electronics    3250000
Groceries      1660000
Clothing       1145000
Furniture      1045000
Beauty          665000
Sports          835000
dtype: int64

## Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [21]:
expensive_store=np.argmax(df_cost.sum(axis=1))
print(df_cost.index[expensive_store])

Mumbai

## Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [22]:
lowest_cost_store=np.argmin(df_cost.sum(axis=1))
print(df_cost.index[lowest_cost_store])

Pune

## Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [29]:
Expensive_Product_Category=np.argmax(df_cost.sum(axis=0))
print(df_cost.columns[Expensive_Product_Category])

Electronics

# Part 6: Profit Analysis Using Two Arrays

## Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

```python
profit_data = sales_data - cost_data
```

Display the complete profit matrix.

In [31]:
profit_data = sales_data - cost_data
df_profit=pd.DataFrame(profit_data,index=stores,columns=categories)
print(df_profit)

           Electronics  Groceries  Clothing  Furniture  Beauty  Sports
Bengaluru       210000     105000     90000      70000   65000   65000
Hyderabad       190000     110000     85000      85000   70000   70000
Chennai         220000      95000     95000      65000   65000   60000
Mumbai          260000     120000    110000      95000   85000   85000
Pune            160000      95000     75000      55000   60000   60000

## Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [25]:
Store_Wise_Profit=pd.Series(sales_data.sum(axis=1)-cost_data.sum(axis=1),index=stores)
print(Store_Wise_Profit)

Bengaluru    605000
Hyderabad    610000
Chennai      600000
Mumbai       755000
Pune         505000
dtype: int64

## Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [29]:
category_Wise_Profit=pd.Series(sales_data.sum(axis=0)-cost_data.sum(axis=0),index=categories)
print(category_Wise_Profit)

Electronics    1040000
Groceries       525000
Clothing        455000
Furniture       370000
Beauty          345000
Sports          340000
dtype: int64

## Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

Display:

* Store name
* Total sales
* Total cost
* Total profit

In [2]:
store_sales = max(df_sales.sum(axis=1))
store_cost = max(df_cost.sum(axis=1))
store_profit = max(df_sales.sum(axis=1)) - max(df_cost.sum(axis=1))
top_store_name = np.argmax(max(df_sales.sum(axis=1)) - max(df_cost.sum(axis=1)))
print(f"Store name: {df_sales.index[top_store_name]}\nTotal sales: {store_sales}\nTotal cost: {store_cost}\nTotal profit: {store_profit}")

Store name: Bengaluru
Total sales: 2820000
Total cost: 2065000
Total profit: 755000

## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [90]:
df_profit=df_sales-df_cost
lowest_profit_store=np.argmin(df_profit.sum(axis=1))
print(df_profit.index[lowest_profit_store])

Pune

## Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [3]:
df_profit=df_sales-df_cost
highest_profit=np.argmax(df_profit.sum(axis=0).values)
print(df_profit.columns[highest_profit])

Electronics

## Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [5]:
df_profit=df_sales-df_cost
lowest_profit=np.argmin(df_profit.sum(axis=0).values)
print(df_profit.columns[lowest_profit])

Sports

## Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

* Profit amount
* Store name
* Product category

Use `np.unravel_index()`.

In [4]:
flat_index = np.argmax(df_profit.values)
row_idx, col_idx = np.unravel_index(flat_index, df_profit.shape)

print(f"Profit amount: ₹{df_profit.values[row_idx, col_idx]}")
print(f"Store name: {df_profit.index[row_idx]}")
print(f"Product category: {df_profit.columns[col_idx]}")

Profit amount: ₹260000
Store name: Mumbai
Product category: Electronics

## Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [7]:
flat_index = np.argmin(df_profit.values)
row_idx, col_idx = np.unravel_index(flat_index, df_profit.shape)

print(f"Profit amount: ₹{df_profit.values[row_idx, col_idx]}")
print(f"Store name: {df_profit.index[row_idx]}")
print(f"Product category: {df_profit.columns[col_idx]}")

Profit amount: ₹55000
Store name: Pune
Product category: Furniture

# Part 7: Profit Margin Analysis

## Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

```python
profit_margin = (profit_data / sales_data) * 100
```

Round the result to two decimal places.

In [5]:
profit_margin = (df_profit/ sales_data) * 100
print(profit_margin)

           Electronics  Groceries   Clothing  Furniture     Beauty     Sports
Bengaluru    24.705882  25.000000  29.032258  25.454545  34.210526  28.888889
Hyderabad    24.358974  23.913043  28.813559  27.419355  33.333333  29.166667
Chennai      23.913043  24.358974  27.941176  25.000000  35.135135  27.906977
Mumbai       24.761905  23.529412  29.333333  27.536232  34.000000  29.310345
Pune         23.188406  23.456790  26.785714  24.444444  34.285714  29.268293

## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100

In [20]:
Store_Wise_Profit=pd.Series(sales_data.sum(axis=1)-cost_data.sum(axis=1),index=stores)
Store_Wise_Sales=pd.Series(sales_data.sum(axis=1),index=stores)
Store_profit_margin=(Store_Wise_Profit/Store_Wise_Sales)*100
print(Store_profit_margin)

Bengaluru    26.651982
Hyderabad    26.579521
Chennai      25.974026
Mumbai       26.773050
Pune         25.505051
dtype: float64

## Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [21]:
Product_Wise_Profit=pd.Series(sales_data.sum(axis=0)-cost_data.sum(axis=0),index=categories)
Product_Wise_Sales=pd.Series(sales_data.sum(axis=0),index=categories)
Product_profit_margin=(Product_Wise_Profit/Product_Wise_Sales)*100
print(Product_profit_margin)

Electronics    24.242424
Groceries      24.027460
Clothing       28.437500
Furniture      26.148410
Beauty         34.158416
Sports         28.936170
dtype: float64

## Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [24]:
highest_overall_profit_store=np.argmax(Store_profit_margin)
print(df_profit.index[highest_overall_profit_store])

Mumbai

## Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [30]:
highest_overall_profit_product=np.argmax(Product_profit_margin)
print(df_profit.columns[highest_overall_profit_product])

Beauty

## Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

In [51]:
profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100

mask = profit_margin < 22

print("Low-Margin Transactions:")
print("Store | Category | Sales | Cost | Profit | Profit Margin")

for i, j in zip(*np.where(mask)):
    print(
        stores[i],
        categories[j],
        sales_data[i, j],
        cost_data[i, j],
        profit_data[i, j],
        round(profit_margin[i, j], 2)
    )

Low-Margin Transactions:
Store | Category | Sales | Cost | Profit | Profit Margin

In [ ]:
# Part 8: Boolean Filtering

## Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [58]:
high_sale_value=df_sales>500000
print("Stores | Categories | High Sales Values")
for i,j in zip(*np.where(high_sale_value)):
    print(stores[i],categories[j],sales_data[i,j])

Stores | Categories | High Sales Values
Bengaluru Electronics 850000
Hyderabad Electronics 780000
Chennai Electronics 920000
Mumbai Electronics 1050000
Mumbai Groceries 510000
Pune Electronics 690000

## Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [69]:
high_sale_value=df_sales<200000
result=[]
for i,j in zip(*np.where(high_sale_value)):
    result.append([stores[i],categories[j],sales_data[i,j]])
df_high_sale_value=pd.DataFrame(
    result,
    columns=["Stores", "Categories", "High sale values"]
)
print(df_high_sale_value)

      Stores Categories  High sale values
0  Bengaluru     Beauty            190000
1    Chennai     Beauty            185000
2       Pune     Beauty            175000

## Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [72]:
high_sale_value_combinations=df_sales>150000
result=[]
for i,j in zip(*np.where(high_sale_value_combinations)):
    result.append([stores[i],categories[j],sales_data[i,j]])
df_high_sale_value_combinations=pd.DataFrame(
    result,
    columns=["Stores", "Categories", "High sale values"]
)
df_high_sale_value_combinations

       Stores   Categories  High sale values
0   Bengaluru  Electronics            850000
1   Bengaluru    Groceries            420000
2   Bengaluru     Clothing            310000
3   Bengaluru    Furniture            275000
4   Bengaluru       Beauty            190000
5   Bengaluru       Sports            225000
6   Hyderabad  Electronics            780000
7   Hyderabad    Groceries            460000
8   Hyderabad     Clothing            295000
9   Hyderabad    Furniture            310000
10  Hyderabad       Beauty            210000
11  Hyderabad       Sports            240000
12    Chennai  Electronics            920000
13    Chennai    Groceries            390000
14    Chennai     Clothing            340000
15    Chennai    Furniture            260000
16    Chennai       Beauty            185000
17    Chennai       Sports            215000
18     Mumbai  Electronics           1050000
19     Mumbai    Groceries            510000
20     Mumbai     Clothing            375000
21     Mumbai    Furniture            345000
22     Mumbai       Beauty            250000
23     Mumbai       Sports            290000
24       Pune  Electronics            690000
25       Pune    Groceries            405000
26       Pune     Clothing            280000
27       Pune    Furniture            225000
28       Pune       Beauty            175000
29       Pune       Sports            205000

## Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

In [ ]:
moderate_sales = np.logical_and(
    sales_data >= 250000,
    sales_data <= 500000
)

result = []

for i, j in zip(*np.where(moderate_sales)):
    result.append([
        stores[i],
        categories[j],
        sales_data[i, j]
    ])

df_result = pd.DataFrame(
    result,
    columns=["Stores", "Categories", "Sales"]
)

df_result

       Stores Categories   Sales
0   Bengaluru  Groceries  420000
1   Bengaluru   Clothing  310000
2   Bengaluru  Furniture  275000
3   Hyderabad  Groceries  460000
4   Hyderabad   Clothing  295000
5   Hyderabad  Furniture  310000
6     Chennai  Groceries  390000
7     Chennai   Clothing  340000
8     Chennai  Furniture  260000
9      Mumbai   Clothing  375000
10     Mumbai  Furniture  345000
11     Mumbai     Beauty  250000
12     Mumbai     Sports  290000
13       Pune  Groceries  405000
14       Pune   Clothing  280000

## Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

In [73]:
moderate_sales = np.logical_and(
    sales_data > 500000,
    df_profit > 150000
)

result = []

for i, j in zip(*np.where(moderate_sales)):
    result.append([
        stores[i],
        categories[j],
        sales_data[i, j]
    ])

df_result = pd.DataFrame(
    result,
    columns=["Stores", "Categories", "Sales"]
)

df_result

      Stores   Categories    Sales
0  Bengaluru  Electronics   850000
1  Hyderabad  Electronics   780000
2    Chennai  Electronics   920000
3     Mumbai  Electronics  1050000
4       Pune  Electronics   690000

## Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

In [74]:
moderate_sales = np.logical_and(
    sales_data < 250000,
    profit_margin < 25
)

result = []

for i, j in zip(*np.where(moderate_sales)):
    result.append([
        stores[i],
        categories[j],
        sales_data[i, j]
    ])

df_result = pd.DataFrame(
    result,
    columns=["Stores", "Categories", "Sales"]
)

df_result

  Stores Categories   Sales
0   Pune  Furniture  225000

## Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

In [103]:
conditions = [
    sales_data >= 500000,
    (sales_data >= 250000) & (sales_data <= 499999),
    sales_data < 250000
]

choices = ["High", "Medium", "Low"]

Category_Performance_Classification = np.select(
    conditions,
    choices,
    default="Unknown"
)

print(Category_Performance_Classification)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]

# Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [104]:
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

## Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

In [118]:
current_sales=sales_data.sum(axis=0)
print("Categories | sales_data | Target Sales | Difference")
for index, (sales, target) in enumerate(zip(current_sales, sales_targets)):
    difference = sales - target
    print(categories[index], sales, target, difference)

Categories | sales_data | Target Sales | Difference
Electronics 4290000 800000 3490000
Groceries 2185000 450000 1735000
Clothing 1600000 320000 1280000
Furniture 1415000 300000 1115000
Beauty 1010000 200000 810000
Sports 1175000 230000 945000

## Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

In [ ]:
target_achievement = sales_data >= sales_targets
print(target_achievement)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]

## Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [133]:
result=[]
for i,j in zip(*np.where(target_achievement)):
    result.append([
        stores[i],
        categories[j]
    ])

Target_Achievement_Count=pd.DataFrame(result)
Target_Achievement_Count

            0            1
0   Bengaluru  Electronics
1   Hyderabad    Groceries
2   Hyderabad    Furniture
3   Hyderabad       Beauty
4   Hyderabad       Sports
5     Chennai  Electronics
6     Chennai     Clothing
7      Mumbai  Electronics
8      Mumbai    Groceries
9      Mumbai     Clothing
10     Mumbai    Furniture
11     Mumbai       Beauty
12     Mumbai       Sports

## Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [149]:
target_achievement = sales_data >= sales_targets
target_count = target_achievement.sum(axis=1)
best_index = np.argmax(target_count)
best_store = stores[best_index]

print("Best Target-Performing Store:", best_store)

Best Target-Performing Store: Mumbai

## Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [151]:
target_achievement = sales_data >= sales_targets
target_count = target_achievement.sum(axis=0)
best_index = np.argmax(target_count)
best_category = categories[best_index]

print("Best Target Achievement by Category:", best_category)

Best Target Achievement by Category: Electronics

## Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use: Variance = Actual Sales - Target Sales

In [152]:
current_sales=sales_data.sum(axis=0)
print("sales_data | Target Sales | Difference")
for sales, target in zip(current_sales, sales_targets):
    difference = sales - target
    print(sales, target, difference)

sales_data | Target Sales | Difference
4290000 800000 3490000
2185000 450000 1735000
1600000 320000 1280000
1415000 300000 1115000
1010000 200000 810000
1175000 230000 945000

## Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

Percentage Variance = (Actual Sales - Target Sales) / Target Sales × 100

In [153]:
current_sales=sales_data.sum(axis=0)
print("sales_data | Target Sales | Percentage Variance")
for sales, target in zip(current_sales, sales_targets):
    Percentage_Variance = (sales - target)/target*100
    print(sales, target, Percentage_Variance)

sales_data | Target Sales | Percentage Variance
4290000 800000 436.25
2185000 450000 385.55555555555554
1600000 320000 400.0
1415000 300000 371.6666666666667
1010000 200000 405.0
1175000 230000 410.8695652173913

## Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [160]:
electronics_sales = sales_data[:, 0]
missing_electronics = stores[electronics_sales < sales_targets[0]]
print(missing_electronics)

['Hyderabad' 'Pune']

## Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use `np.all()`.

In [162]:
target_achievement = sales_data >= sales_targets
all_targets = np.all(target_achievement, axis=1)
print(all_targets)

[False False False  True False]

## Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

In [163]:
target_achievement = sales_data >= sales_targets
any_targets = np.any(target_achievement, axis=1)
print(any_targets)

[ True  True  True  True False]

# Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [164]:
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

## Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

In [165]:
discount_amount = sales_data * discount_rates

print(discount_amount)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]

## Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [166]:
net_sales = sales_data - discount_amount

print(net_sales)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]

## Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [167]:
new_profit = net_sales - cost_data

print("New Profit:")
print(new_profit)

New Profit:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]